Fix POSTCOMPILE expansion in SQLAlchemy 1.4.27+
googleapis/python-bigquery-sqlalchemy pull request #408
Opened 2022-02-03 09:39 UTC by jethron

Handle the new double underscore prefix for POSTCOMPILE variables introduced in SQLAlchemy 1.4.27 onwards. (See commit [sqlalchemy#f79df12bd6d99b8f6f09d4bf07722638c4b4c159](https://github.com/sqlalchemy/sqlalchemy/commit/f79df12bd6d99b8f6f09d4bf07722638c4b4c159))

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-sqlalchemy/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Related to #385 🦕

Actually encountered this issue in `pybigquery` (dependency for [great_expectations](https://greatexpectations.io/)), not sure if there's a backporting process or if that's just completely unsupported now?

2022-02-10 23:59 UTC, tswast commented
> Actually encountered this issue in pybigquery (dependency for [great_expectations](https://greatexpectations.io/)), not sure if there's a backporting process or if that's just completely unsupported now?

We don't have the resources to backport to `pybigquery`.

2022-02-11 11:03 UTC, jethron commented
> > Actually encountered this issue in pybigquery (dependency for [great_expectations](https://greatexpectations.io/)), not sure if there's a backporting process or if that's just completely unsupported now?
> 
> We don't have the resources to backport to `pybigquery`.

All good, thought I'd ask. :)

Not sure what the deal is with the compliance tests. Pushed a commit that gets it at least running for 3.8 on my local but not sure it'll pass... Any advice?

2022-02-16 02:51 UTC, jethron commented
Ah, I see!
Thanks, force pushed again without that commit.

2022-02-17 18:30 UTC, tswast commented
@jethron It looks like you haven't enabled "allow commits from maintainers".

Could you sync with main and also update `setup.py` to allow SQLAlchemy 1.4.27?

2022-02-17 22:41 UTC, tswast approved these changes

2022-02-18 06:15 UTC, jethron commented
Think that fixes the failing test. Not positive on what that line does, so I've just wrapped it in the same if-guard for 1.4.27+. Can I get another force-run?

2022-02-18 14:57 UTC, tswast requested changes

2022-02-18 15:08 UTC, tswast commented on sqlalchemy_bigquery/base.py
> +                param = param.replace(")", f":{bq_type})")
Looking at the failing test, there ends up with an extra trailing parentheses and the type information doesn't appear to have been extracted.

```
[SQL: select id FROM some_table WHERE z IN (%(q_1)s, %(q_2)s, %(q_3)s:STRING) ORDER BY id]
```

It does seem this change is necessary, but I wish I understood what had changed in 1.4.27 that requires it.

2022-02-18 16:11 UTC, tswast commented on sqlalchemy_bigquery/base.py
> +            if self.__sqlalchemy_version_info < (1, 4, 27):
Looks like we're missing unit test coverage of entering the `if bindparam.expanding` if statement, but SQLAlchemy >= 1.4.27

```
sqlalchemy_bigquery/base.py                481      0    172      1    99%   531->541
```

I would have thought that the update to `setup.py` would make sure the tests run, though. 🤔

2022-02-22 15:08 UTC, tswast approved these changes

2022-02-22 16:16 UTC, merged

2022-02-22 16:57 UTC, tswast commented
Thanks so much for the contribution @jethron ! I'm planning on releasing these changes today in 1.4.0 https://github.com/googleapis/python-bigquery-sqlalchemy/pull/415