chore: add custom sync repo settings
googleapis/python-bigquery-sqlalchemy pull request #412
Opened 2022-02-09 16:55 UTC by parthea

2022-02-10 16:10 UTC, busunkim96 commented
@parthea There seem to be samples in this repo: https://source.cloud.google.com/results/invocations/028324d7-0c47-4143-8084-7d97d28de548/targets/github%2Fpython-bigquery-sqlalchemy%2Fsamples%2Fsnippets/tests

2022-02-14 05:37 UTC, shollyman commented
Deferring LGTM on this one to swast, I'm not sure if the sqlalchemy workflows needs any customization.

2022-02-14 21:10 UTC, tswast requested changes

2022-02-14 21:10 UTC, tswast commented on .github/sync-repo-settings.yaml
> +    - 'Kokoro prerelease'
Let's not block PR merges due to prerelease failures. I do want to know about them and get flakeybot issues, though.

2022-02-14 21:10 UTC, tswast commented on .github/sync-repo-settings.yaml
> +    - 'Kokoro SQLAlchemy compliance'
I'm undecided as to whether we should block PRs for this. They can take hours to run and we don't have direct control over them, so I'm inclined to say they shouldn't be blocking (but if they're broken we should fast-follow with a fix)

2022-02-14 21:10 UTC, tswast commented on .github/sync-repo-settings.yaml
> +    - 'Kokoro SQLAlchemy compliance'
Side note: it'd be lovely if we could have this block release PRs only.

2022-02-14 21:55 UTC, tswast commented on .github/sync-repo-settings.yaml
> +    - 'Kokoro prerelease'
Using a suggested commit so I can resolve my previous comments.

```suggestion
```

2022-02-14 21:56 UTC, tswast approved these changes

2022-02-14 21:56 UTC, tswast commented
@parthea I think this will require an admin to merge due to missing GH Actions tests.

2022-02-15 15:35 UTC, tswast commented
Note: Failing Kokoro tests should be fixed by #401 , but that's blocked waiting on review and also this change to GH Actions requirements.

2022-02-15 15:36 UTC, merged