[Fixes #428] Add MERGE DDL
googleapis/python-bigquery-sqlalchemy pull request #429
Opened 2022-03-17 18:57 UTC by munro

Throwing over some code I'm currently using to generate `MERGE` statements.  Overall I really like that API, and it feels really slick.  One thing that is missing is `ThenUpdate` / `ThenInsert` doesn't check if the key actually exists on the `into` table—which may be desirable in the instance the developer didn't describe the table in SQLAlchemy (I often use it like that).  But it would be nice to check if the column does exist if the schema is defined.

Fixes #428 🦕🙌🆒

2022-03-22 13:44 UTC, tswast commented
@munro Thanks so much for the contribution. I hope to review soon. Unfortunately, I cannot merge this without the account associated with your commit (I see a kw.com email) signing the Google CLA at https://cla.developers.google.com/clas

2022-03-22 13:54 UTC, tswast requested changes
Very cool! A few initial comments, though the CLA issue will also need to be resolved.

2022-09-23 02:15 UTC, pykenny commented
Any updates to this PR?

Also, merge statement in BigQuery allows more complicated case branching like:
```sql
MERGE INTO target AS t
USING source AS s
ON t.id == s.id
-- Special cases
WHEN MATCHED AND s.expire_at <= CURRENT_DATETIME() THEN DELETE
WHEN NOT MATCHED BY SOURCE AND t.expire_at <= CURRENT_DATETIME() THEN DELETE
WHEN NOT MATCHED AND (s.flag_a == 2) THEN INSERT ...
-- Defaults
WHEN MATCHED THEN UPDATE ...
WHEN NOT MATCHED BY SOURCE THEN UPDATE SET ...
WHEN NOT MATCHED THEN INSERT ...
-- Unreachable cases
WHEN MATCHED THEN UPDATE ...
WHEN NOT MATCHED BY SOURCE THEN UPDATE SET ...
WHEN NOT MATCHED THEN INSERT ...
```

Which means:
 * Filtering condition not only is applicable to "matched" but also can be applied to the other two cases ("not matched by source/target").
 * All three merge situation clauses, no matter having additional filtering condition or not, can be repeated as long as having valid syntax (parser doesn't care about unreachable case)

2022-09-23 02:26 UTC, pykenny commented
`NOT MATCHED BY SOURCE` and `MATCHED` cases allows delete and update (but not insert) operations, while `NOT MATCHED (BY TARGET)` only allows insert operation. I think that constraint is absent in current implementation as well.

2022-09-23 12:24 UTC, munro commented on sqlalchemy_bigquery/merge.py
> +import textwrap
Added!

2022-09-23 12:24 UTC, munro commented on sqlalchemy_bigquery/merge.py
> +    ...
Fixed!

2022-09-23 12:25 UTC, munro commented on sqlalchemy_bigquery/merge.py
> +from dataclasses import dataclass
https://github.com/googleapis/python-bigquery-sqlalchemy/blob/f5663718c4727a55157e8f0cdd95c371311498aa/setup.py#L98

Ah went to go add it, but I see it now requires `python >= 3.7` 😄

2022-09-23 12:25 UTC, munro commented on tests/unit/test_merge.py
> +import sqlalchemy as sa
Fixed!

2022-09-23 13:07 UTC, munro commented
@pykenny Oh wow, thank you, I didn't even know you could have multiple of the same when conditions.  I read the documentation [1] and made it match.

I don't like the syntax (currently).

I really wanted to avoid 'piping', but IDK, it may be nicer...?

```python
merge = Merge(
    target=target,
    source=source,
    on=into.c.b == using.c.b
)

merge = merge.when_matched(target.foo > 10).then_insert({"foo": source.foo})
merge = merge.when_matched_not_matched_by_source().then_delete()
```

... it does kinda look nice. 😄 

Also contemplating a 'partial' piping syntax:


```python
Merge(
    target=target,
    source=source,
    on=into.c.b == using.c.b,
    when=[
        Merge.WhenMatched(target.foo > 10).then_insert({"foo": source.foo})
    ]
)
```




[1] https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#merge_statement

2022-09-26 06:03 UTC, pykenny commented on sqlalchemy_bigquery/merge.py
> +        return MergeWhenNotMatchedBySource(self, condition)
Shouldn't they be `when_not_matched_by_target` and `when_not_matched_by_source`? 🤔

2022-09-26 07:43 UTC, pykenny commented on sqlalchemy_bigquery/merge.py
> +    return "WHEN MATCHED NOT MATCHED BY SOURCE" + _compile_when(
`WHEN MATCHED NOT MATCHED BY SOURCE` -> `WHEN NOT MATCHED`

2022-11-18 01:43 UTC, pykenny commented on sqlalchemy_bigquery/merge.py
> +class Merge(ClauseElement):
`ClauseElement` instance is not executable, so passing a `Merge` instance to `Connection.execute()` doesn't work.

```python
updates = {"id": source.id, "name": source.name}
stmt = (
  Merge(target, source, on=target.id == source.id)
  .when_matched()
  .then_update(updates)
  .when_not_matched_by_target()
  .then_insert(updates)
)
connection.execute(stmt)
```

How about inheriting [`UpdateBase`](https://docs.sqlalchemy.org/en/14/core/dml.html#sqlalchemy.sql.expression.UpdateBase)?

2022-12-15 07:48 UTC, pykenny commented
@munro Would it be possible to make it support ORM models as well? Users may want to write this:

```python
from sqlalchemy.orm import aliased
...

alias_dest = aliased(MyModelDest)
alias_source = aliased(MyModelSource)

Update(
    alias_dest,
    alias_source,
    on=...,
).when_matched().then_update(...)
```

2023-04-04 19:24 UTC, meredithslota commented
Unfortunately, we can't accept contributions without a signed CLA. This has been open for a while with a couple comments to this effect, and while I can tell it would be helpful, we can't accept it as-is. See https://github.com/googleapis/python-bigquery-sqlalchemy/pull/429#issuecomment-1075198520 and our [CONTRIBUTING guide](https://github.com/googleapis/python-bigquery-sqlalchemy/blob/main/CONTRIBUTING.rst) for more info.

2023-04-04 19:24 UTC, closed without merging

2023-12-30 03:10 UTC, munro commented
> @munro Thanks so much for the contribution. I hope to review soon. Unfortunately, I cannot merge this without the account associated with your commit (I see a kw.com email) signing the Google CLA at https://cla.developers.google.com/clas

@meredithslota I just signed the CLA! [1] Signed it because I see activity in the PR #428 

[1] https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_INDIVIDUAL

2024-07-31 16:09 UTC, JacobHayes commented
Can this be reopened or resubmitted now that the CLA is signed?